# Generated by Django 5.2.8 on 2025-11-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariant',
            new_name='Variant',
        ),
    ]
