# Generated by Django 5.2.8 on 2025-12-01 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sellerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='phone_number',
        ),
    ]
