# Generated by Django 5.2.8 on 2025-12-02 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_variant_product_productvariant_delete_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='features/icons/'),
            preserve_default=False,
        ),
    ]
