# Generated by Django 5.2.8 on 2025-12-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
