# Generated by Django 5.2.8 on 2025-12-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_sellerprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
