# Generated by Django 5.2.8 on 2025-12-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
